# Environment
language: objective-c
env:
  - DEBUG=1
  - DEBUG=0

# Install build dependencies
before_script:
  - brew install boost libyaml python node protobuf v8
  - sudo npm install -g less@1.3.0
  - sudo npm install -g coffee-script@1.4.0
  - sudo npm install -g handlebars@1.0.10
  - sudo npm install -g mocha
  - gem install ruby_protobuf

# Build script
script:
  - ./configure
  - make -j 3 test-deps DEBUG=$DEBUG
  - make test TEST=travis RUN_TEST_ARGS='-j3 -w-' DEBUG=$DEBUG

notifications:
  # Email commit author only on build status change
  email:
    on_success: change
    on_failure: change

  # Always ping a webhook when something is broken. The webhook looks
  # only for builds in next, and notifies everyone on the dev team
  # that next is broken. This isn't currently possible directly with
  # Travis.
  webhooks:
    urls:
      - https://zapier.com/hooks/catch/n/ux03n/
    on_success: never
    on_failure: always

